require("user.general")
require("user.keymaps")
require("user.plugins")
require("user.theme")
require("user.ts")
require("user.autopairs")
require("user.cmp")
require("user.indent")
require("user.icons")
require("user.bufferline")
require("user.telescope")
require("user.which-key")
require("user.lsp-inlayhints")
require("user.lsp")
require("user.symbol-outline")
require("user.mason")
require("user.null-ls")
-- require("user.git-blame")
-- require("user.nvim-tree")
-- require("user.statline")
-- require("user.lualine")
-- require("user.gitsigns")
-- require("user.tabnine")
